[Newbis]
[0]
[ShortDescription]Start Room[/Short Description]
[LongDescription]This is the starting area[/LongDescription]
[North]1[/North]
[/0]
[1]
[ShortDescription]Another Room[/ShortDescription]
[LongDescription]This is another room[/LongDescription]
[South]0[/South]
[East]2[/East]
[/1]
[2]
[ShortDescription]Some Other Room I Guess[/ShortDescription]
[LongDescription]This is just some other room I suppose[/LongDescription]
[West]1[/West]
[/2]
[/Newbis]