[Newbis]
[0]
[LongDescription]This is the starting area[/LongDescription]
[North]1[/North]
[ShortDescription]Start Room[/ShortDescription]
[/0]
[1]
[East]2[/East]
[LongDescription]This is another room[/LongDescription]
[North]3[/North]
[ShortDescription]Another Room[/ShortDescription]
[South]0[/South]
[/1]
[2]
[LongDescription]This is just some other room I suppose[/LongDescription]
[ShortDescription]Some Other Room I Guess[/ShortDescription]
[West]1[/West]
[/2]
[3]
[LongDescription]Room created in game[/LongDescription]
[ShortDescription]New Room[/ShortDescription]
[South]1[/South]
[/3]
[/Newbis]
