[Parent]
[AnAttribute]First[/AnAttribute]
[AnotherAttribute]Second[/AnotherAttribute]
[ChildNode]
[ChildAttribute]CHILD[/ChildAttribute]
[/ChildNode]
[ChildNode2]
[ChildAttribute2]CHILD2[/ChildAttribute2]
[ChildNode3]
[AnotherAttribute]FDSA[/AnotherAttribute]
[ThisIsAttribute]ASDF[/ThisIsAttribute]
[/ChildNode3]
[/ChildNode2]
[ListOfThings]
One
Two
Three
[/ListOfThings]
[/Parent]
